spring:
  application:
    name: sistema-gestion-reportes
  
  profiles:
    active: dev
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# Configuración de almacenamiento de archivos
app:
  upload:
    dir: ${user.home}/uploads/reportes
  jwt:
    secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationPleaseChangeInProduction}
    expiration: 86400000 # 24 horas en milisegundos
  
  scheduler:
    enabled: true
    cron:
      alerts: "0 0 8 * * ?" # Ejecutar diariamente a las 8 AM

# Configuración de Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: false

---
# Perfil de desarrollo
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/reportes_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  mail:
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.reto.spring.llanogas: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# Perfil de producción
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/reportes_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-binding-errors: never

logging:
  level:
    com.reto.spring.llanogas: INFO
